development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: sleep-overflow_development
  pool: 5

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: sleep-overflow_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: sleep-overflow_production
  pool: 5
